CANONICAL_ALLOWED_GENRES = frozenset(
    [
        "acoustic",
        "alternative",
        "alternative rock",
        "ambient",
        "avant jazz",
        "blues",
        "chillout",
        "classic rock",
        "country",
        "dance",
        "dream pop",
        "easy listening",
        "electro",
        "electronic",
        "electronica",
        "experimental",
        "experimental rock",
        "folk",
        "funk",
        "hard rock",
        "heavy metal",
        "hip hop",
        "house",
        "indie",
        "indie pop",
        "indie rock",
        "instrumental",
        "instrumental rock",
        "jazz",
        "jazz rock",
        "leftfield",
        "metal",
        "pop",
        "post punk",
        "progressive rock",
        "punk",
        "rnb",
        "rock",
        "shoegaze",
        "soul",
        "synth pop wave",
        "trip hop",
    ]
)

GENRE_ALIAS_TO_CANONICAL = {
    "avant-jazz": "avant jazz",
    "dream-pop": "dream pop",
    "hip hop": "hip hop",
    "hip-hop": "hip hop",
    "left field": "leftfield",
    "left-field": "leftfield",
    "post-punk": "post punk",
    "r&b": "rnb",
    "rhythm and blues": "rnb",
    "synth-pop wave": "synth pop wave",
    "trip-hop": "trip hop",
}
